tasks:
  # random utilities
  - name: utils
    before: |
      sudo apt-get install tree

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      echo "Installing AWS CLI..."
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf awscliv2.zip aws
      echo "AWS CLI installation complete"
      cd $THEIA_WORKSPACE_ROOT
    command: |
      echo "AWS CLI version:"
      aws --version
      bash